### ISSUE TITLE
Url parameters need to be encoded

### ISSUE THREAD

**Issue by bernd70** [db85/garmin_export#2]
If you have a stron password with special characters like "&" the url paramater needs to be encoded.

I changed AuthService.cs:PostLogin():

NameValueCollection formData = new NameValueCollection
{
  { "username", Uri.EscapeDataString(UserName) },
  { "password", Uri.EscapeDataString(Password) },
  { "embed", "true" }
};

Cant't say if there are other places where escaping is required.

Greetings
Bernd

**Comment by db85** [comment]
Thanks for the hint. Has been fixed with the last commit
